application:
  vehicle-distance-topic: "output_topic"
  vehicle-signal-topic: "input_topic"

server:
  port: 8080
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled: true

spring:
  application:
    name: rest-service
  kafka:
    bootstrap-servers:
      ${SPRING_KAFKA_BOOTSTRAP_SERVERS:http://localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone:
        ${EUREKA_URI:http://localhost:8761/eureka}
